### ISSUE TITLE
Large balances don't render correctly

### ISSUE THREAD

**Issue by vcarl** [stellar/account-viewer#104]
### What did you do?

Loaded an account with a large balance (>=1000XLM)

### What did you expect to see?

```
Your balance:
1000.0000000
```

### What did you see instead?

```
Your balance:
.
```

**Comment by vcarl** [comment]
It looks like this began after #95 was merged, something about the formatting seems to break it

**Comment by Fellow70** [comment]
Do I understand correct? stellar account can carry only a few lumens now to be transfered by Ledger nano S?

**Comment by vcarl** [comment]
There was a bug related to the balance being shown, the balance on the account was not affected.
