### ISSUE TITLE
Memo

### ISSUE THREAD

**Issue by irisli** [stellar/account-viewer#12]
Work in progress: https://github.com/stellar/account-viewer/tree/memo
## Text and messages

| memo type | placeholder | error message |
| --- | --- | --- |
| MEMO_TEXT | A string up to 28 characters long | <code>MEMO_TEXT</code> must contain a maximum of 28 characters |
| MEMO_ID | A 64 bit unsigned integer | <code>MEMO_ID</code> must be a valid 64 bit unsigned integer |
| MEMO_HASH | A 32 byte hash | <code>MEMO_HASH</code> must be a 32 byte hash represented in hexadecimal (A-Z0-9) |
| MEMO_RETURN | A 32 byte hash | <code>MEMO_RETURN</code> must be a 32 byte hash represented in hexadecimal (A-Z0-9) |
## No-memo state

> ![image](https://cloud.githubusercontent.com/assets/5728307/10955798/4eb32194-830b-11e5-92e4-5ceac3e1744f.png)
## Memo setup state

After _Add memo_ is clicked, the memoSetup element appears and defaults to MEMO_TEXT

> ![image](https://cloud.githubusercontent.com/assets/5728307/10955807/65b6bb08-830b-11e5-99dd-cee6c7088f72.png)
## Memo setup with error state

Note: the text in this screenshot is out of date. Refer to the **Text and messages** section for the correct messages

> ![image](https://cloud.githubusercontent.com/assets/5728307/10955959/595fd956-830c-11e5-8420-6632edca6ad2.png)

**Comment by bartekn** [comment]
Added memo logic in https://github.com/stellar/account-viewer/commit/9fd90653f9be3f15c25a29b510994964effc1c40. Should we also display a memo in a confirmation step?

**Comment by irisli** [comment]
Thats a good idea. Can you add it to the scope of the confirmation step and i'll add it to the ui tomorrow
