### ISSUE TITLE
Limit precision in send pane

### ISSUE THREAD

**Issue by irisli** [stellar/account-viewer#16]
I'm able to do this without errors in the send building. But if I submit this transaction, I get a OP_UNDERFUNDED.

![image](https://cloud.githubusercontent.com/assets/5728307/11007116/9d91e512-847c-11e5-90c6-4547ff8cfefa.png)

**Comment by bartekn** [comment]
Fixed in js-stellar-base: https://github.com/stellar/js-stellar-base/commit/6e7fa477a9bac86aedb6d2900ecd27be172f2c97. Will close this after releasing new `stellar-base` version.
