### ISSUE TITLE
Make lumens amount after the decimal be a lighter color

### ISSUE THREAD

**Issue by irisli** [stellar/account-viewer#17]
This should take just a few minutes. Not all cultures have the same use for the comma and period so it would be nice to have one more visual cue of where the decimal is

**Comment by vcarl** [comment]
For other faded items, we're using #717577 for text color

**Comment by Chirag175** [comment]
I'd like to take this issue. I'm new to the stellar community and this would be my first contribution here.

**Comment by Chirag175** [comment]
Hoping this https://github.com/stellar/account-viewer/pull/95#issue-342597800 solves the problem. I'd like to state that I wasn't able to install and have a running clone on my system. I would like someone to assist me with the same. However, as the issue could be solved entirely on the front-end in just a single line, I went forward with it.

**Comment by vcarl** [comment]
Thanks @Chirag175! What issues did you run into running it locally? Would love to help address those, happy to chat in Keybase (I'm vcarl there as well) if you want to try and get it working.

**Comment by vcarl** [comment]
Closed in #95
