### ISSUE TITLE
npm install ko: ed25519

### ISSUE THREAD

**Issue by FredericHeem** [stellar/account-viewer#18]
`npm install` fails when it tries to compile `ed25519`.

```
../src/ed25519.cc:10:49: error: no member named 'New' in 'v8::String'
        return ThrowException(Exception::Error(String::New(msg)));
```

Version:
`npm 2.14.4`
`node v4.1.1`

**Comment by bartekn** [comment]
What version of g++ do you have? You need at least 4.8.

**Comment by FredericHeem** [comment]
```
$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```

`js-stellar-base` can be installed without any issue though.

**Comment by bartekn** [comment]
Fixed in https://github.com/stellar/interstellar-sessions/commit/3ace5747d867fd5700c0958d46b5f0fea665a72f. Thanks @FredericHeem!
