### ISSUE TITLE
"MEMO_NONE" vs "No memo" in Transaction History

### ISSUE THREAD

**Issue by irisli** [stellar/account-viewer#25]
Should we say `MEMO_NONE` or `No memo` (or something else)?

`MEMO_NONE` is indeed a term used in code: https://github.com/stellar/stellar-core/blob/308540543c3b9f059fc50c06f74ec30b70e4ea0d/src/xdr/Stellar-transaction.x#L244

However, I wonder if it is the most user friendly.

![image](https://cloud.githubusercontent.com/assets/5728307/11637004/d69df304-9cd3-11e5-8c8b-abd2b9912fc1.png)

**Comment by jedmccaleb** [comment]
you shouldn't print anything there at all

**Comment by irisli** [comment]
Ok, I agree with you jed.
