### ISSUE TITLE
Memo shouldn't be removed when a new accountId is entered

### ISSUE THREAD

**Issue by irisli** [stellar/account-viewer#32]
Steps to reproduce:
1. Add memo
2. Add AccountId

One might want to add the memo first just to make sure they don't forget the memo. But what happens is that doing it in this order makes the memo actually not be there, leading to sending a transaction missing its intended memo.

**Comment by wriches** [comment]
Just encountered this issue myself, and lost quite a few XLM in the process :(

**Comment by bartekn** [comment]
Fixed in https://github.com/stellar/account-viewer/pull/41
