### ISSUE TITLE
Make TestNet logins available

### ISSUE THREAD

**Issue by MikeFair** [stellar/account-viewer#38]
I like the solution as created for #9 but on the sign-in page I'd like to be able to sign in to TestNet (for lots of purposes).  Account-Viewer gives us developers a somewhat "official" way to demonstrate our code is doing the right thing (if I write some code on my laptop and someone can refresh their stellar.org Account-Viewer on TestNet view; and sees the appropriate changes reflected; that's a independent validation that the code actually worked).

As someone just cobbling together some first scripts; having these tools on TestNet would greatly improve those "I'm doing it right" validation moments for code/people looking at it through distributed endpoints.

**Comment by jedmccaleb** [comment]
Yeah I agree it is useful. But these wallets all support testnet accounts: stargazer, stellar-portal, my_wallet, starwallet  So we probably won't add this to the account viewer.
https://galactictalk.org/d/14-projects-built-on-stellar

**Comment by MikeFair** [comment]
I'll take that to mean "not going to focus anytime soon (if ever), but also
not opposed to a PR if a decent one should show up" :)

**Comment by jedmccaleb** [comment]
yep :)
