### ISSUE TITLE
Indicate more evidently that the private key shown is shown only once.

### ISSUE THREAD

**Issue by juan-cortes** [stellar/account-viewer#53]
After reading [this post](https://www.reddit.com/r/Stellar/comments/7t3xp8/psa_on_the_importance_of_your_private_key_and_my/) and feeling bad for the guy I feel this change is trivial enough to save a lot of people having issues. Perhaps a simple styling for the private key and a warning message, an alert asking for confirmation. It's a one-liner.

**Comment by rdrey** [comment]
Also came here inspired by the same post to try and help out.

**Comment by BrentLabasan** [comment]
Stellar Desktop's warnings about savings your private key are a good example. It even asks you to check if you're in an area where people can see your typing or if video recorders are around.

**Comment by fnando** [comment]
Just submitted a PR for this:

https://github.com/stellar/account-viewer/pull/54
