### ISSUE TITLE
Offline use

### ISSUE THREAD

**Issue by thinkloop** [stellar/account-viewer#56]
For maximum security it is best never to expose keys to an online machine, by generating wallets, and signing transactions completely offline. This client is very close to being able to do that, but doesn't quite work offline. If I download the page as a single file with all dependencies and scripts inlined using the plugin [Save Page WE](https://chrome.google.com/webstore/detail/save-page-we/dhhpefjklgkmgeafimnjhojgjamoafof), the page loads but the buttons are non responsive - no errors display in the console. This is the file that is generated: https://ufile.io/w8s2r 

It seems like enabling offline functionality is a few tweaks away, are there any plans to implement it?

Here is a bitcoin-centric tool implemented in such a fashion: https://coinb.in/

Online activities, like reading balances or broadcasting transactions could be optional.

Thanks.

**Comment by vcarl** [comment]
Hm thinking about this, I'm not clear what use this has offline. There are only really 2 features: showing balances and sending simple payments, both of which require network. I suppose you could verify that a private key is valid?

At any rate, I'm going to close this as it's not something we're going to work on right now.
