### ISSUE TITLE
Allow encoded XDR of signed payment to be viewed before submitting

### ISSUE THREAD

**Issue by pselden** [stellar/account-viewer#58]
Would you me amenable to a PR allowing the signed transaction XDR to be viewed before submitting it? This would allow you to use the account viewer even if multi-sig is enabled (letting you copy it so you can send it to another signer).

I'm thinking possibly of some expandable section or a dialog containing the XDR that opens when you press a link.

**Comment by pselden** [comment]
Closes #66

**Comment by bartekn** [comment]
Closed in https://github.com/stellar/account-viewer/pull/66
