### ISSUE TITLE
incoming account merge is filtered as a small payment

### ISSUE THREAD

**Issue by tomerweller** [stellar/account-viewer#69]

**Comment by robertDurst** [comment]
Replicated with:
`GBEHR2FTSYMGL7TIIUWTIA27BGBYKK55Y6EZZPPP26ZTHGQGKM7QR3N3`
`SBLY7KTO7YB25UD5KO7LL3SVQVJHCZGJ7UB45YGDRXAC6KX5GIVHV3OI`

These are just testnet ^
