### ISSUE TITLE
Add commas to the large numbers

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/account-viewer#7]
1,000 instead of 1000 in balances and amount to send etc

**Comment by bartekn** [comment]
Sure. For inputs should it add commas while user is typing? Like:

`100` -> user types 0 -> `1,000`

**Comment by jedmccaleb** [comment]
If it is easy sure but that seems less important

**Comment by bartekn** [comment]
Closed in https://github.com/stellar/basic-client/commit/1e64de34f543d804b68bc7eee8731841e4748ce6
