### ISSUE TITLE
How to buildin on Ubuntu/Alpine

### ISSUE THREAD

**Issue by itpromorus** [stellar/account-viewer#78]
Hello!
I have a problem with building in Docker on Ubuntu/Alpine OS.
fsevetns supported only MacOS.
Is it possible to avoid this error on Ubuntu?

`Module not found: Error: Can't resolve 'fs'`

**Comment by vcarl** [comment]
That's usually fine to ignore. The build step for this app is fairly old thought, and requires node 6.x to build correctly. Typically the error when on a node version too new is 
```
TypeError: Cannot read property 'prototype' of undefined
```
