### ISSUE TITLE
indicate to users when they're on testnet

### ISSUE THREAD

**Issue by jessica-collier** [stellar/account-viewer#9]
Users signed in to their testnet account can't view balance. Add a tag indicating the account is on the testnet, not live net.

cc @irisli

**Comment by jedmccaleb** [comment]
The account viewer only points to live on production

**Comment by irisli** [comment]
Instead, i think the message should something along the lines of:

> This account does not exist on the Stellar network yet. Note: the account viewer is only connected to the public Stellar network (and not the test network).

This is also part of a bigger issue is that the `loading` state and the `account not created` state look identical.

**Comment by vcarl** [comment]
Closing this because it's extremely old and there is no mechanism to sign into testnet in the production service
